# Generated by Django 4.1.7 on 2023-05-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_destination"),
    ]

    operations = [
        migrations.RenameField(
            model_name="destination", old_name="name", new_name="title",
        ),
    ]
