# Generated by Django 4.1.7 on 2023-05-17 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_name_destination_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="belonging_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
